### ISSUE TITLE
Logfile Management using Cumulocity

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#1077]
**Is your feature request related to a problem? Please describe.**
Currently thin-edge.io handles only its own log files. However Cumulocity could request all log files from a device.
It would be good if I could manage from Cumulocity side which log files I want to request and get them.

**Describe the solution you'd like**
Cumulocity already provides the supportedLogs Fragment for that. However thin-edge.io needs to push that to the inventory object, e.g. read out from an .toml file. Idealy this .toml would be managed by cumulocity (e.g. configuration files).

**Comment by didier-wenzek** [comment]
A good idea to be implemented along the line of the current work on [configuration management](https://github.com/thin-edge/thin-edge.io/pull/1028).

**Comment by didier-wenzek** [comment]
### Proposal

* Update the `c8y_configuration_plugin` daemon to support `c8y_LogfileRequest` operations.
* Use the same configuration file to list the paths both to the config and log files.
* Both log and config files can be given a name (per default, the file path).
* Remove the current [`log_request_plugin`](https://github.com/thin-edge/thin-edge.io/tree/main/plugins/log_request_plugin) plugin.

### Alternatives
* Maintain distinct daemons for configuration and log requests, trading simplicity for flexibility.
* Have two distinct configuration files to list the config and the log files.

**Comment by mbay-ODW** [comment]
The longer I think of that I personally prefer the alternative solution such that I do have a dedicated daemon for log files and one for configurations. In principle these two plugins are separated functions.

However a distinct configuration file could be used to list the log files.

**Comment by initard** [comment]
@didier-wenzek 
> * Use the same configuration file to list the paths both to the config and log files.

Assuming same configuration file means to use `c8y_configuration_plugin.toml`, **what would it look like**? At the moment it is something like this: 

- Would it look something like this? 

```text
files = [
    '/etc/tedge/tedge.toml',
    '/etc/tedge/mosquitto-conf/c8y-bridge.conf',
    '/etc/tedge/mosquitto-conf/tedge-mosquitto.conf',
    '/etc/mosquitto/mosquitto.conf',
    '/etc/var/log/tedge',
    '/etc/var/log/mosquitto',
  ]
```
----
Or something like this?

```text
files = [
    '/etc/tedge/tedge.toml',
    '/etc/tedge/mosquitto-conf/c8y-bridge.conf',
    '/etc/tedge/mosquitto-conf/tedge-mosquitto.conf',
    '/etc/mosquitto/mosquitto.conf',
  ]

log_files = [
   '/etc/var/log/tedge',
   '/etc/var/log/mosquitto',
]
```

**Comment by initard** [comment]
@didier-wenzek just an obervation. 

Depending on directory permissions _we may or may not require sudo_ to read logs. 

On my machine, I can not read `/etc/var/log/mosquitto/mosquitto.log` unless I am sudo or mosquitto user. 

But I can read `/etc/var/apt/history.log` as any user. 

![image](https://user-images.githubusercontent.com/78221071/164445678-1ece010f-afd9-4c64-831d-488f5ecb8721.png)

**Comment by didier-wenzek** [comment]
@initard 
> Assuming same configuration file means to use `c8y_configuration_plugin.toml`, **what would it look like**? 

If we decide to keep a single configuration file, then we need to have *two independent* lists, a first one for the configuration files, a second ones for the log files.

**Comment by rina23q** [comment]
The purpose of the new log file management is
* To deliver configurable log file management plugin.
* To add the configuration file to the existing log file management plugin so that users can choose which log files to monitor on c8y.

Solutions:
* The log file plugin is independent from the config management plugin.
* Change the log file plugin to daemon.
* The plugin declares the supported log types to c8y. Currently, the c8y mapper declares them. At the daemon start-up and inotify. Use the config management plugin as a blue-print.
* The log file plugin config file is separated from the config-management plugin config file.
* The config file should be the list of glob patterns with names (key as log file type, value as actual glob file patterns), not just the list of paths.

```toml
# example to explain the second bullet point.
log_files = [
   {key = "tedge-log", value = "/var/log/tedge/*"},
]
```

Out of scope:
* Open up `tedge.toml` file to keep also plugin config files.

How to work:
- [ ] Write a short specification for the new log file management plugin like the one for config management.
- [ ] Show it in the sprint demo.
- [ ] Implementation.
