### ISSUE TITLE
Actions job to check whether Cargo.lock is up to date

### ISSUE THREAD

**Issue by matthiasbeyer** [thin-edge/thin-edge.io#1322]
In #1320 we found that `Cargo.lock` was outdated although this PR had nothing to do with `Cargo.lock` or even Rust code.

We should add a job to our actions workflow to check a PR for up-to-date `Cargo.lock` so that these things do not happen anymore (and we don't need PRs such as #1321).

---

One issue I see: If crates get updated but the dependabot PR has not landed yet, this might cause `Cargo.lock` to be outdated in a PR, although really it is not:

```mermaid
gitGraph
    commit

    branch feature-abc
    branch dependabot-update-xyz
    checkout dependabot-update-xyz

    commit id:"Update xyz"

    checkout feature-abc
    commit id:"Implement abc"
```

In above diagram, the actions job for "Implement abc" might fail because it does not yet include the "Update xyz" patch. Rebasing fixes this easily, of course. Is this acceptable or too much of a hassle?

I think it is acceptable. The "Implement abc" patch should not include dependency updates and rebasing is most of the time a no-brainer in this scenario. So once "Update xyz" has landed on "main", the author of "Implement abc" just needs to rebase and update their PR and that's it.

---

The implementation of such a action job might be error prone. Not sure how to do it properly.
Please discuss.

**Comment by matthiasbeyer** [comment]
Maybe it is an option to run `cargo build` with the `--locked` flag?

**Comment by TheNeikos** [comment]
After some testing and discussion it seems that `cargo check --locked` exhibits the wanted behaviour:

- It does not touch existing fulfilled dependencies
- If a dep. does not exist, it would try adding it (and fails due to --locked)
- If a dep. does not have the required version in the .lock file it also fails

This should be enough to have it run whenever a `Cargo.toml` file changes in the repo.
