### ISSUE TITLE
tedge-watchdog.service stays in status activating

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1372]
**Describe the bug**
tedge-watchdog.service stays in status activating after starting it.

**To Reproduce**
Precondition: thin-edge.io is installed on DUT
1. Start the tedge-watchdog service  (`sudo systemctl start tedge-watchdog.service`)
2. Check the systemctl status of tedge-watchdog service (`systemctl is-active tedge-watchdog.service`)

The status remains _**activating**_ all the time

Status will change to _**active**_ only after adding the line _WatchdogSec=30_ in the services section of the`/lib/systemd/system/tedge-mapper-c8y.service`

**Expected behavior**
tedge-watchdog service to have status _**active**_ right after starting the service

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by rina23q** [comment]
AC: Explain what "activating" and "active" state means, and why our `tedge-watchdog` behaves as @gligorisaev reported.

**Comment by PradeepKiruvale** [comment]
As per the below link `Systemd`  service will be in an `Activating` state when it runs in the `watchdog` mode until the `ready` is sent to the systemd.
https://unix.stackexchange.com/questions/638539/how-to-properly-make-a-service-telling-systemd-that-it-is-set-up#:~:text=The%20usual%20answer,at%20this%20point%20*/

With the existing `tedge-watchdog` implementation, there are two threads.

- One that monitors itself
- 2nd thread monitors the `tedge` services

The second thread will be running only if there any of the `tedge` services are enabled with the watchdog feature.
i.e the systemd service file contains `WatchdogSec`, else it will exit. 
When it exits the `tedge-watchdog` fails, so it gets restarted because in its service file `Restart=always` is specified, and it will try to resend the ready state, in that process the `tedge-watchdog` service enters into an `Activating` state.

The disadvantage here is the `tedge-watchdog` will keep restarting until any of the service's `WatchdogSec` is enabled.

The advantage is no need to `Restart` the `tedge-watchdog` when any service updates its `systemd` service file with `WatchdogSec`. (But not really good idea, because it consumes CPU and power)

So I updated the `Restart=on-failure` in the `tedge-watchdog` service file. Now if the `tedge-watchdog` is started, it will move to an `inactive` state if the `WatchdogSec` is not enabled for any of the `tedge` services.

If any `tedge` service has to be monitored then one has to update the corresponding `systemd` service file and then restart the `tedge-watchdog`.

So, the proposed fix is 

`
--- a/configuration/init/systemd/tedge-watchdog.service
+++ b/configuration/init/systemd/tedge-watchdog.service

 [Service]
 Type=notify
 ExecStart=/usr/bin/tedge_watchdog
**-Restart=always
+Restart=on-failure**
 WatchdogSec=30

`

**Comment by rina23q** [comment]
@PradeepKiruvale Your proposal makes sense. So, what we can work now

* Change the `tedge-watchdog.service` as you proposed.
* Update https://thin-edge.github.io/thin-edge.io/html/howto-guides/021_enable_tedge_watchdog_using_systemd.html accordingly.
