### ISSUE TITLE
tedge-agent documentation

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1470]
**Is your documentation request related to a problem? Please describe.**
Document the `tedge-agent`
-Architecture
-Features
-Interfaces with the mapper
-Interaction with the plugins

**Describe the improvement you'd like**

**Additional context**

**Comment by didier-wenzek** [comment]
The agent documentation has been updated: https://github.com/thin-edge/thin-edge.io/pull/2235

**Comment by didier-wenzek** [comment]
The section  https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/references/agent/index.md,
describe the expected behavior of tedge-agent:

- How to run-it on the main device as well as on a child device.
- How to restart the main device or a child device.
- How to install software on the main device or a child device.

**Comment by didier-wenzek** [comment]
A more detailed list of what has been implemented is provided here: https://github.com/thin-edge/thin-edge.io/issues/2018
