### ISSUE TITLE
Improved error handling for child device support of c8y-configuration-plugin

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1480]
**Is your feature improvement request related to a problem? Please describe.**

While requesting a config snapshot from the child device, if the child device send the successful operation status without uploading the config snapshot file, thin-edge should mark that operation as failed in the cloud even though the child device wrongly reports that the operation is successful. Currently the plugin crashes when it fails to download the config snapshot file from the file-transfer service that it expected the child device to upload.

Similarly, the config download/upload operations in the cloud must be failed if the download/upload of the child device config artefacts from the cloud fails, before they can even be shared with the child devices. 

To simplify the config snapshot management in the plugin, the uploaded artefacts from the file-transfer-service may be read/updated/deleted directly from the file system instead of using HTTP GET/PUT/DELETE.

**Comment by gligorisaev** [comment]
**c8y-configuration-plugin crash examples:**

`mosquitto_pub -h 192.168.1.120 -t "tedge/CD18102022160629$/commands/res/config_snapshot" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}`
instead of:
`c8y-configuration-plugin crash examples:
mosquitto_pub -h 192.168.1.120 -t "tedge/CD18102022160629/commands/res/config_snapshot" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}
`
please note the $ sign in the child device id

**Different typo errors in the command and the crush of the plugin:**
`mosquitto_pub -h 192.168.1.120 -t "tedge/CD18102022160629/commands/res/config_snapshot" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}'`
`mosquitto_pub -h 192.168.1.120 -t "tedge/CD18102022160629/commands/res/config_snapshots" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}'`
`mosquitto_pub -h 192.168.1.120 -t "tedge/CD18102022160629/commands/res/config_snapshot" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}'`
`mosquitto_pub -h 192.168.1.120 -t "tedge/CD18102022160629/commands/res/config_snapshot" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}'`

at this point plugin crushes with following message:

LOG
`2022-10-19T10:17:37.836266497Z  INFO c8y_configuration_plugin: config snapshot response`
`2022-10-19T10:17:37.836617485Z  INFO c8y_configuration_plugin::upload: Downloading the config file snapshot uploaded by the child device from url: http://192.168.1.120:8000/tedge/file-transfer/CD18102022160629$/config_snapshot/file_a`
`Error: JSON parse error: "HTTP status client error (404 Not Found) for url (http://192.168.1.120:8000/tedge/file-transfer/CD18102022160629$/config_snapshot/file_a)"`

Plugin started again

`mosquitto_pub -h 192.168.1.120 -t "tedge/CD18102022160629/commands/res/config_snapshot" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}'`

at this point plugin crushes again

LOG:
`2022-10-19T10:22:34.067159033Z  INFO c8y_configuration_plugin: config snapshot response`
`2022-10-19T10:22:34.067344449Z  INFO c8y_configuration_plugin::upload: Downloading the config file snapshot uploaded by the child device from url: http://192.168.1.120:8000/tedge/file-transfer/CD18102022160629/config_snapshot/file_a`
`Error: JSON parse error: "HTTP status client error (404 Not Found) for url (http://192.168.1.120:8000/tedge/file-transfer/CD18102022160629/config_snapshot/file_a)"`


Plugin started again

`mosquitto_pub -h 192.168.1.12 -t "tedge/CD18102022160629/commands/res/config_snapshot" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}'
^[OAError: No route to host`

`mosquitto_pub -h 192.168.1.120 -t "tedge/CD18102022160629/commands/res/config_snapshot" -m '{"status": "successful", "path": "/home/pi", "type": "file_a", "reason": null}'`

at this point plugin crushes again

LOG:
`2022-10-19T10:26:06.246069061Z  INFO c8y_configuration_plugin: config snapshot response`
`2022-10-19T10:26:06.246265675Z  INFO c8y_configuration_plugin::upload: Downloading the config file snapshot uploaded by the child device from url: http://192.168.1.120:8000/tedge/file-transfer/CD18102022160629/config_snapshot/file_a`
`Error: JSON parse error: "HTTP status client error (404 Not Found) for url (http://192.168.1.120:8000/tedge/file-transfer/CD18102022160629/config_snapshot/file_a)"`

**Comment by albinsuresh** [comment]
Tests Cases

Improvements made in #1502 which can be tested with build https://github.com/thin-edge/thin-edge.io/actions/runs/3323067864 are:

* If a child device sends a successful response to a `config_snapshot` request without uploading the config file to thin-edge file repository, the operation in the cloud is failed.
* If thin-edge fails to download the config file specified in the URL field of `c8y_DownloadConfigFile` request, that operation is failed in the cloud, **without** even forwarding that request as a `config_update` request to the child device.
* When child device sends bad response (invalid JSON response) to `config_update` or `config_snapshot` requests from thin-edge, that failure is not just logged but the operation is failed in the cloud as well.
* If the plugin receives a request for a config-type that's not listed in the child device's `c8y-configuration-plugin.toml`, the plugin ignores that request with a warning in the log that it is an unknown type. The operation in the cloud is **not** failed, to give a chance for some other software to process that request.
