### ISSUE TITLE
Revert the use of 80 as the default HTTP port in favor of 8000

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1486]
Using the port 80 for HTTP has more cons that pros.

Sure, using 80 makes things more naturel, but:
* this adds complexity for the agent which needs to start as `root` and to substitute for the `tedge` once the port open,
* this might conflict with another HTTP server on the thin-edge gateway, 
* in any cases the external devices will have to know the IP address of the thin-edge gateway: adding the port number is not an issue.

Proposal:
* Use the port 8000 as a default for file transfer.
* This default will be made configurable with https://github.com/thin-edge/thin-edge.io/issues/1479
* Keep the agent running as tedge (and using `sudo` access explicitly and specifically granted)

AC:
* Update the agent to use the port 8000 for file transfer.
* Update the systemd config to run the agent as tedge.
* Update the file transfer documentation.
* Make sure the c8y_configuration plugin uses the port 8000 and sends this info to the child devices.

**Comment by albinsuresh** [comment]
@gligorisaev This PR just changes the HTTP port number of the agent from 80 to 8000. The child devices in your tests will have to be adapted to connect to this new port during their bootstrap.

But, before installing this version, make sure that you purge the previous installation and also manually delete `/var/tedge` directory, because this directory unfortunately isn't purged by the uninstall script of the previous version. It has been fixed now in the latest version.
