### ISSUE TITLE
Mosquitto config replace `message_size_limit` with `max_packet_size`

### ISSUE THREAD

**Issue by scharri** [thin-edge/thin-edge.io#1491]
**Describe the bug**
If you start mosquitto in verbose mode you will get the note about using `max_packet_size` instead `message_size_limit`.

**To Reproduce**
Start mosquitto and look at the output:
sudo mosquitto -v -c /etc/mosquitto/mosquitto.conf

**Expected behavior**
No information about using an alternative option instead used option.

**Screenshots**
![2022-10-17 12_21_16-Clipboard](https://user-images.githubusercontent.com/4233022/196153840-813dd6e5-0e65-439c-b9e2-29dbeea3462a.png)

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Hardware: Raspberry Pi 4 Model B Rev 1.4
 - System-Architecture: Linux raspberrypi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux
 - thin-edge.io version: 0.7.5

**Additional context**
-

**Comment by rina23q** [comment]
Hi @scharri, can you tell us your mosquitto version?

**Comment by scharri** [comment]
Hi @rina23q my mosquitto version is: 2.0.11

**Comment by reubenmiller** [comment]
From first look the main differences in the [docs](https://mosquitto.org/man/mosquitto-conf-5.html) between the settings are:

* `max_packet_size` applies a limit the whole message (not just payload)
* `message_size_limit` applies a limit to the message's payload size

So it looks like we can make the change (assuming all of the integration tests don't pick up anything unexpected)

**Comment by reubenmiller** [comment]
We might need to rethink the default value, as Cumulocity default MQTT payload limit is `16384` bytes. There is a semi-related ticket regarding this #1415

Otherwise if we did not want to impose the limit to the local MQTT broker, we could limit the bridge max package size setting via `bridge_max_packet_size`. But again we need to be careful about mismatches between the local and bridge MQTT brokers so that messages don't get silently swallowed without being propagated to the cloud.

**Comment by didier-wenzek** [comment]
Apologize: I respond to this question off-line but failed to report the response here.

* `max_packet_size` is meaningful only for MQTT v5 while thin-edge use MQTT v3.1.1.
* `message_size_limit is supported by both versions ... but requires a code change since we need then to check for any error code returned attached to the ACK messages.

So this is not a simple fix.

**Comment by reubenmiller** [comment]
Since we don't have short term plans to support MQTT v5 we will close this issue.
