### ISSUE TITLE
Correctly trap errors/failures through the Operation plugin framework

### ISSUE THREAD

**Issue by NeilCondon** [thin-edge/thin-edge.io#1527]
**Is your feature improvement request related to a problem? Please describe.**
The operations plugin publishes its own “EXECUTING” and “SUCCESS” notifications to the topic “c8y/s/us” using SmartREST templates 501 & 503 respectively.   But unlike sm-plugins, it appears to ignore the exit code of the custom plugin script.   This means that every custom operation - whether successful or not - is registered as successful by a Cumulocity tenant.

**Describe the solution you'd like**
Ideally, the operations plugins would behave the same as the sm-plugins:  Trapping exit codes other than “0” and mapping the output of stderr to the “Failure reason” field of the original operation object in c8y.

**Describe alternatives you've considered**
An alternative would be to return to the methodology implied in the current documentation, where the plugin doesn’t generate any SmartREST responses, but instead relies on the plugin script to take care of notifying Cumulocity.   See below…

**Additional context**
The functionality currently described in the documentation (which is different that what is implemented) is that the custom script should take care of generating success/failure notifications:

[https://thin-edge.github.io/thin-edge.io/html/tutorials/supported_operations.html](url)

> In this example we want thin-edge.io to pick up a message on specific topic and execute the command on the device, our topic is c8y/s/ds. We also know that the message we expect is going to use SmartRest template 511 and our plugin is located in /etc/tedge/operations/command. Then we need to add the configuration to the file (/etc/tedge/operations/c8y/c8y_Command):
>```
>[exec]
>  topic = "c8y/s/ds"
>  on_message = "511"
>  command = "/etc/tedge/operations/command"
>```
>And now the content of our command plugin:
>```
>#!/usr/bin/sh
>mosquitto_pub -t c8y/s/us -m 501,c8y_Command
>OUTPUT=$(echo $1)
>mosquitto_pub -t c8y/s/us -m 503,c8y_Command,"$OUTPUT"
>```
>This simple example will execute the command echo $1 and send the result back to the cloud

**Comment by NeilCondon** [comment]
On reflection, I think that **returning to to the documented behaviour is the more scalable/future-proof option**...

Consider the situation where a **child device** is listening to the "c8y/s/ds" or "c8y/s/dc" topics, looking for a custom Operation that is supported by both thin-edge.io _and_ the child device:
- The custom plugin on thin/edge will be triggered for all messages (regardless of whether thin/edge is the target device).  So the custom plugin running on thin-edge.io will have to examine the SmartREST payload to determine if the Operation is intended for it, or the child device.
- If the Operation is targetted at the _child device_, it must do nothing - including NOT sending an EXECUTING response to the platform - and trust that the child device will respond appropriately to the Operation.

I think the only way to accomplish this is to make EXECUTING, FAILED and SUCCESS responses the responsibility of the custom operation script, and not generated by thin/edge based on the outcome of the script.

**Comment by reubenmiller** [comment]
I didn't see this before I created a similar ticket. #1603

I suspect there will not be a one-size-fits-all solution when it comes to who is responsible for updating the operation status.

But maybe first a bit of background about plugins and some of the goals of `tedge`.

Currently there are two approaches to writing a custom plugin like the `c8y_Command` handler:

### Option 1: Service based plugin

The service base plugin has an always running service, and `tedge` only triggers a signal via a custom defined interface (e.g. DBUS, REST, file-based queue etc.)

**Advantages**
* Can handle unexpected errors such as OOM killer (but still relying on each plugin to implement the same logic)

**Disadvantages**
* More complex and takes longer to implement
* Wasteful with resources as it is always running even when there is no operation

### Option 2: Script based plugin

The plugin is only launched when an operation is received. Once the operation action is completed, the plugin process exits.

**Advantages**
* Uses less memory because it is only run on demand
* Easy to implement

**Disadvantages**
* Can't resume an already in process operation if it is killed by the OOM Killer or if the device is restarted unexpectedly

---
Though one of the goals we are trying to achieve is to make writing a robust agent easier. And this means that we don't just push the "harder to implement" aspects on the plugin authors.

So some of the design goals would be to:

* Provide common mechanisms (state persistence, resuming interrupted operations etc.)
* Abstract cloud interactions from the plugins so that plugins remain cloud agnostic
* Don't always assume that plugin authors know the cloud implementation details and do the right thing.

Though the your point regarding the scalability aspect is very important (especially when it comes to child devices). So I think we will still have be open to special cases when the plugin knows better than `tedge`, but this interaction could be abstracted to still achieve the "agnostic cloud" goal.

**Comment by NeilCondon** [comment]
I guess another option for the "Script-based plugin" is for thin/edge to only trigger the script if the SmartREST device_id matches thin/edge's id.   Your point about plugins remaining cloud agnostic is an important consideration, and I don't know how this would play with operations (or their equivalent) generated by platforms other than C8y (Azure etc.) - e.g. whether they are smart enough to identify the target device in the payloads they send...
Another alternative, of course, is to make the response handling behaviour configurable throught the config file in `/etc/tedge/operations/<whatever>`.

**Comment by reubenmiller** [comment]
Yes I would probably opt for the configurable option to make it more flexible.

There are already some steps underway looking at how to handle the dispatching of operations based on the target device, so that the wrong device does not get invoked.
