### ISSUE TITLE
Refactor `get-thin-edge_io.sh` script to download the `thin-edge.io zip package` to install.

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1546]
**Is your refactoring request related to a problem? Please describe.**
`thin-edge.io` is released as multiple different packages.i.e tedge, tedge_mapper, tedge_agent, plugin packages etc, for 
 for every supported platform (amd64, aarch64, armv7, armhf). This will be too many packages to download.

Also, there are naming conflicts for the same package for different platforms. For example, the tedge package for `armv7` and `armhf` will be named as `tedge_0.7.7_armhf.deb`. Because of this restriction and the existing release scheme, only one package can be released. So, the `installation` script will download the same package for both platforms, and hence installation fails.

**Describe the solution you'd like**
So, the proposal is to use the `zipped` package per platform as is produced by the `GitHub` actions. This will help the installation script to download one `zip` package, unzip and install it on the device.

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
I would recommend to use the `tar.gz` format as the `zip` utility is not installed by default on many linux distributions.

**Comment by PradeepKiruvale** [comment]
As of now, we will create the `tar` packages of the Debian packages per architecture. The installation script will download, untar and install those Debian packages onto the device.

**Comment by reubenmiller** [comment]
Looking on the planned packaging/hosting topics. We can close this as we will focus on way to install the packages via `apt-get` rather than downloading the packages manually. Also we are looking do publish some official docker images which will also remove the need to install the package on non-debian based linux operating systems.

Due to the current complexities of the maintenance scripts (e.g. the additional scripts/commands that need to be run before the service is usable), preparing a usable tar format is out of scope.
