### ISSUE TITLE
Child device name in c8y gets "MQTT Device" prefix

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1569]
**Describe the bug**
By recreating deleted child device in c8y, the Child device name gets "MQTT Device" Prefix

**To Reproduce**
1. Create a child device with given name
2. Observe the name of the device, it is like declared during creation
3. Delete the device
4. Create the Device again
5. Observe that the child device got "MQTT Device" prefix

**Expected behavior**
The name of the device to be as declared during creation

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by rina23q** [comment]
Regarding the step 3, how do you create the device again?

**Comment by 6367f766** [comment]
# How to test

This PR fixes child devices being prefixed with "MQTT Device". This issue was occurring because supported operations were being sent to devices deleted in the cloud. This is now fixed and can be tested as follows:

- Create a child device with given name
- Observe the name of the device, it is like declared during creation
- Delete the device
- **Restart tedge-mapper** / **Create device again** (both should work and should be tested)
- Observe the name of the device is again declared

This PR changed the logic of how supported devices are declared, so previous tests may or may not be broken. Have a look for tests that touch on:

- Sending measurement for child devices
- Sending configuration for child devices (upload & download)
