### ISSUE TITLE
tedge service init session error message is not verbose enough

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1778]
**Describe the bug**

When the `tedge` services are installed using dpkg or apt if the mqtt broker is not running then it will fail to create a session.
The error message that is printed out not verbose enough.
```
2023-03-01T01:29:43.407495831Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-mapper-c8y.lock"
2023-03-01T01:29:43.407713732Z  INFO tedge_mapper::c8y::mapper: Initialize tedge mapper c8y
Connection Error I/O: Connection refused (os error 111)
The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

2023-03-01T01:29:43.468065155Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-mapper-az.lock"
2023-03-01T01:29:43.468158555Z  INFO tedge_mapper::az::mapper: Initialize tedge mapper az
Connection Error I/O: Connection refused (os error 111)
The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

2023-03-01T01:29:43.533035895Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-mapper-aws.lock"
2023-03-01T01:29:43.533153996Z  INFO tedge_mapper::aws::mapper: Initialize tedge mapper aws
Connection Error I/O: Connection refused (os error 111)
```
**To Reproduce**
Stop the mosquito broker `sudo systemctl stop mosquitto.service`
Install tedge mapper `sudo dpkg -i tedge-mapper*.deb`

This will print the error message, `Connection Error I/O: Connection refused (os error 111)`

**Expected behavior**
A more verbose message telling that the service failed to create the session with mqtt broker.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by reubenmiller** [comment]
Though it is just about being "more verbose" it is about telling the user that this is actually ok, or expected to happen if the mosquitto broker is not running when the installation happens (e.g. when creating a container image and installing each tedge component, mosquitto will not be running)

**Comment by reubenmiller** [comment]
Here is the suggested message that should be printed on INFO level (instead of the above OS error)

```
Could not register MQTT session as the broker is currently unavailable
```

**Comment by didier-wenzek** [comment]
> Could not register MQTT session

I'm not sure this is appropriate, as might let think that the TCP connection has been established but that the MQTT connection failed for some other reason.

> Though investigate if we can add some additional detailed info (e.g. is the broker unavailable, invalid credentials etc.)

We have such details. The issue is more to translate those into something meaningful.

* [ConnectionError](https://docs.rs/rumqttc/latest/rumqttc/enum.ConnectionError.html)
* [ConnectReturnCode](https://docs.rs/rumqttc/latest/rumqttc/mqttbytes/v4/enum.ConnectReturnCode.html)

**Comment by rina23q** [comment]
My quick investigation.

This call produces the error message (Caution! It's not treated as error in terms of a program. We just print the error on stderr and the code returns `Ok(())`).

https://github.com/thin-edge/thin-edge.io/blob/1b307601c731490b86d48824a1d6ddced4fca9eb/crates/core/tedge_mapper/src/core/component.rs#L18


`mqtt_channel::init_session()` addresses `ConnectionError`, which is defined in `rumqttc`.
https://docs.rs/rumqttc/latest/rumqttc/enum.ConnectionError.html
https://github.com/thin-edge/thin-edge.io/blob/fed2101b9299a99159e03849dc957fac87b7ddbe/crates/common/mqtt_channel/src/session.rs#L42-L45


```rust
pub enum ConnectionError {
    MqttState([StateError](https://docs.rs/rumqttc/latest/rumqttc/enum.StateError.html)),
    NetworkTimeout,
    FlushTimeout,
    Websocket([Error](https://docs.rs/http/0.2.8/x86_64-unknown-linux-gnu/http/error/struct.Error.html)),
    WsConnect([Error](https://docs.rs/rumqttc/latest/rumqttc/v5/enum.TlsError.html)),
    Tls([Error](https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html)),
    Io(Error),
    ConnectionRefused([ConnectReturnCode](https://docs.rs/rumqttc/latest/rumqttc/mqttbytes/v4/enum.ConnectReturnCode.html)),
    NotConnAck([Packet](https://docs.rs/rumqttc/latest/rumqttc/mqttbytes/v4/enum.Packet.html)),
    RequestsDone,
}
```

In this report, we just hit the `IoError::ConnectionRefused`, which is defined in `std::io` https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html. 

---

Since there many possibilities to fail, it's difficult to address all patters to improve error message. If the word "Error" scares users, can we just replace the word "Error" like below?

From
https://github.com/thin-edge/thin-edge.io/blob/fed2101b9299a99159e03849dc957fac87b7ddbe/crates/common/mqtt_channel/src/session.rs#L43
To
```rust
eprintln!("Couldn't connect to broker {}", err);
```

**Comment by reubenmiller** [comment]
> I'm not sure this is appropriate, as might let think that the TCP connection has been established but that the MQTT connection failed for some other reason.

I was trying to work it very generically which meant "we could not pre-register the client, don't worry this might not be an error" (or something to that effect)...though I can see how mentioning 'session' could lead to people thinking the TCP connection was ok, but the MQTT part was not.

**Comment by rina23q** [comment]
To be honest, now it's not clear enough to me what I can do. I can propose two variations.

1. Rephrase `eprintln!("Connection Error {}", err); ` only.
2. Make a special case for the error `ConnectionError(IoError::ConnectionRefused)` to output some special message.

**Comment by PradeepKiruvale** [comment]
I think we must indicate that it `failed to connect to local broker`.

**Comment by gligorisaev** [comment]
tested and ok
