### ISSUE TITLE
Firmware plugin download blocking child device response processing

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1782]
**Describe the bug**

When the `c8y-firmware-plugin` is busy downloading a firmware binary as part of a firmware update **request** processing, it blocks the whole message processing thread, preventing the processing of any firmware update **responses** from other child devices at the same time. If the firmware file is huge and the download takes several hours to complete, no responses will be processed and this is not desirable. This can even lead to operations timing out in the cloud even when the child device has sent a response within the timeout window.

**To Reproduce**

1. Push a firmware update request to a child device with a small file and wait till the corresponding `tedge/commands/req` is sent to that child device.
2. Push a firmware update request to a second child device with a large file which will take some time to download
3. While the plugin is downloading the file, send an `executing` firmware update response from the first child device
4. Observe that the response from the first child device is not processed and propagated to the cloud

**Expected behavior**

Responses from child devices should be processed independently of requests from the cloud being processed. One should not block the other for too long.

**Comment by didier-wenzek** [comment]
Fixing this kind of issues is one of the benefits of the new design using actors. To handle long-running download requests a firmware actor has simply to configure its message box to receive the download response messages along all the other requests and responses, instead of being forced to wait for that response in a blocking manner. This adds the need to manage some state for the on-going download but opens the way to many improvements as not only end-of-download messages but also download-progress messages.

I will add an example in `tedge_actors` documentation on how to implement this using actors.

I'm afraid this will not directly help here. An option is to implement the download part using an actor and plug this actor into the current implementation (leveraging the fact an actor doesn't require the runtime to work).

**Comment by albinsuresh** [comment]
> I'm afraid this will not directly help here. An option is to implement the download part using an actor and plug this actor into the current implementation (leveraging the fact an actor doesn't require the runtime to work).

Yes, the plan was to mimic a `DownloadManager` actor which will be spawned as just a tokio task in the current impl, which can easily be ported later into a dedicated actor in the actor variant of this plugin.

**Comment by albinsuresh** [comment]
### Test Case

#### Setup

* The `c8y-firmware plugin` is installed and running on tedge device
* 2 connected child devices with firmware management enabled for them in the cloud (Run `tedge mqtt pub c8y/s/us/<child-id> 114,c8y_Firmware` for all child devices)

#### Test

1. Send a firmware update request for `child 1` from the cloud
2. Wait till `child 1` receives the mapped `tedge/command/req/firmware_update` request but do not send any response yet
3. Send a firmware update request with a large firmware file for `child 2` so that the download takes time
4. While the download is in progress for this request for `child 2`, send a `tedge/command/res/firmware_update` response from `child 1`
5. Verify that the response from `child 1` is processed and forwarded to the cloud immediately, even when the download for child 2 is still in process.

**Comment by gligorisaev** [comment]
Tested and it is fixed
