### ISSUE TITLE
Child support for azure iot hub

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#1799]
**Is your feature request related to a problem? Please describe.**
Currently there is no child support for azure iot hub.
To make a component of thin-edge.io which acts as a child, cannot be simply connected to azure.

First I thought about az iot [modules] (https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly-as-a-module) but each module needs a separate mqtt connection to az. 
I also tried to create a separate bridge for each module, but it seems, that it is not possible to share the same certificate for device and module.

Therefore I looked for another sulution and found this: [Using components](https://learn.microsoft.com/en-us/azure/iot-develop/tutorial-multiple-components?pivots=programming-language-ansi-c)
=> It's possible to attach poperties to telemetry data. In this case a component name is added to the message. Thereby it's possible to send data from different "component" (e.g. childs of thin-edge) to az using one shared mqtt connection.

To add the `component` name to the message the message have to be send to `device/{device-id}/messages/events/$.sub={child-id}`.

The result in the azure event hub looks like this
for the root device (sending the message `{"temp":12.5}` to `device/{device-id}/messages/events/`):
```
{
    "event": {
        "origin": "demo-device",
        "module": "",
        "interface": "",
        "component": "",
        "payload": "{\"temp\":12.5}"
    }
}
```
for a child device (sending the message `{"temp":12.5}` to `device/{device-id}/messages/events/$.sub={child-id}`):
```
{
    "event": {
        "origin": "demo-device",
        "module": "",
        "interface": "",
        "component": "child1",
        "payload": "{\"temp\":12.5}"
    }
}
```

**Describe the solution you'd like**
The mapper has to be extend to forward measurements from `tedge/measurements/{child-id}` to `az/messages/events/$.sub={child-id}`.
The `az-bridge.conf` has to be changed: 
```
< topic messages/events/ out 1 az/ devices/{device-id}/
---
> topic messages/events/# out 1 az/ devices/{device-id}/
```

**TODO**
Check if it's possible to get a similar solution for methods and device twin.

**Comment by reubenmiller** [comment]
@toewsar Thanks for the details ticket, much appreciated.

It took be a while to find a reference to the actual topic structure using the `$.sub=` syntax, until I clued on that they use url encoding, e.g. `%24.sub=` in some of the documentation, [example](https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/iot-central-connect-device-c.md). I'm actually really surprised how difficult it is to find useful information about all of the supported MQTT topics for Azure, so I really appreciate the details provided in this ticket.

Looking at the [module](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly-as-a-module) documentation, it looks like that you need a separate device certificate per module, and use the id in the form of `{device-id}/{module-id}`, so that definitely adds a lot more complexity, so I would also agree that the "component" structure looks to be the simpler approach.

We should be able to map thin-edge child device information to `device/{device-id}/messages/events/%24.sub={child-id}` easily enough, I'd have to check if we can do the mapping just in the bridge settings, or whether the az mapper needs to do this translation, but that is just implementation details.
