### ISSUE TITLE
New configuration option to disable lock file creation

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1802]
**Is your feature improvement request related to a problem? Please describe.**

Whe deploying thin-edge components in single-process containers, the lock file mechanism used by some components (e.g. `tedge-agent`, `tedge-mapper`) do not makes sense as the container filesystem is isolated. Having the lock file system just adds unnecessary dependencies on the `/run/lock` folder.

**Describe the solution you'd like**

Add a new configuration option under the `[run]` section to turn off the lock file generation logic.

```toml
[run]
lock_files = false
```

Having this configuration setting allows the user to set it using a common environment setting when running the components in individual containers.

**Describe alternatives you've considered**

An alternative solution would be to add a new cli flag to each of the binaries (e.g. `tedge-agent --no-lock`). Though with this solution will be harder to use for components which don't generate a lock file, so the user will be guess whether they need to provide the `--no-lock` flag or not.

**Additional context**

**Comment by didier-wenzek** [comment]
I have a mix feeling about this request. On one side, it's pointless to have a lock file in a container (really pointless as the point of this lock is to prevent two processes fighting for the same MQTT session name: even if a lock is enforced in each container, two processes spawned in two different containers will fight for that session name). On the other side, having an option to ignore a lock defeats the core purpose of locks (I'm pretty sure that this option will be abused instead of trying to understand a conflict). So I wonder if it would be better to remove locks once and for all. The issue would be then to find a better strategy to avoid one wild process consuming the messages targeting another one. 

We also have to consider how this will be combined with https://github.com/thin-edge/thin-edge.io/issues/1746.

**Comment by gligorisaev** [comment]
Default value for lock file creation:
`run.lock_files=true`

In order to prevent the creation of lock file:
`sudo tedge config set run.lock_files false`

In order to enable the creation of lock file:
`sudo tedge config unset run.lock_files`
and
`sudo tedge config set run.lock_files true`

QUESTION: why for dissabling creation of lock files 
`sudo tedge config set run.lock_files` is failing
and
`sudo tedge config unset run.lock_files` is not?
