### ISSUE TITLE
Documentation tests are not running in tedge crate

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#186]
**Describe the bug**
We have some documentation tests in tedge crate (e.g. commands.rs), but they are not executed by `cargo test`.

**To Reproduce**
Run `cargo test`.
The problem is tedge is binary project. Rustdoc's documentation tests can run only for library project.

**Expected behavior**
Do we want to execute documentation tests, don't we? I think the tests written in documentation in tedge should go to tests module.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version] Ubuntu 18.04
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"] Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - thin-edge.io version 0.1.0
 
**Additional context**

**Comment by makr11st** [comment]
Is this still relevant?

**Comment by makr11st** [comment]
@rina23q In general in `rustdoc` tests are not supported over binaries, there was a request to add the feature a few years ago but it didn't get into rust due to problems with how the code could be run: https://github.com/rust-lang/rust/issues/50784 and specifically from [this comment](https://github.com/rust-lang/rust/issues/50784#issuecomment-765624762) to the end of the thread.
In general we may expect this feature in near future but who knows, should we close this issue in this case?

**Comment by rina23q** [comment]
Closing this issue and waiting the feature release is one option. However, we may be able to create a library crate and move those files. In my opinion, APIs requiring how to use descriptions should be in library crate.

**Comment by rina23q** [comment]
It's very minor thing. I'll close it for now.
