### ISSUE TITLE
c8y-remote-access-plugin cleanup fails if support operation has already been deleted

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1869]
**Describe the bug**

Purging `c8y-remote-access-plugin` fails if the `/etc/tedge/operations/c8y/c8y_RemoteAccessConnect` file no longer exists when the purging is executed. This block the removal of the package, and makes it very difficult for users to remove the package (as it requires the user to manually delete the `postrm` script before purging).

**Workaround**

Manually delete the `postrm` script prior to purging the package, or before calling the thin-edge.io uninstall script.

```sh
sudo rm -f /var/lib/dpkg/info/c8y-remote-access-plugin.prerm
curl -sSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/uninstall-thin-edge_io.sh | sudo sh -s purge
```

**To Reproduce**

1. Install thin-edge (include `c8y-remote-access-plugin`)
    ```sh
    curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s
    ```

2. Manually remove the `c8y_RemoteAccessConnect` file

    ```sh
    sudo rm -rf /etc/tedge/operations/c8y/c8y_RemoteAccessConnect
    ```
    **note**
    * Technically this file might not be manually removed by a user, it is more likely that the `tedge-agent` which removes the `/etc/tedge/operations` folder on its post removal script `postrm`

4. Try to uninstall the package

    ```sh
    sudo apt-get purge c8y-remote-access-plugin
    ```

    Or alternatively you can try to purge it using the uninstall script
    
    ```sh
    curl -sSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/uninstall-thin-edge_io.sh | sudo sh -s purge
    ```

Afterwards you may need to reset your setup you may need to delete the prerm file manually (because otherwise your package system may be broken).

```sh
sudo rm -f /var/lib/dpkg/info/c8y-remote-access-plugin.prerm
sudo apt-get purge c8y-remote-access-plugin
```

**Expected behavior**

* `c8y-remote-access-plugin` should not fail on removing a file or folder that does not exist (as the work has already been done, so the action should be idempotent)

**Screenshots**

The following log output shows the `c8y-remote-access-plugin` error log when trying to be purged via the install script.

```sh
$ curl -sSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/uninstall-thin-edge_io.sh | sudo sh -s purge
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  c8y-remote-access-plugin*
0 upgraded, 0 newly installed, 1 to remove and 545 not upgraded.
1 not fully installed or removed.
After this operation, 2446 kB disk space will be freed.
(Reading database ... 75873 files and directories currently installed.)
Removing c8y-remote-access-plugin (0.10.0) ...
Error:
  × Removing supported operation at /etc/tedge/operations/c8y/
  │ c8y_RemoteAccessConnect
  ╰─▶ No such file or directory (os error 2)

dpkg: error processing package c8y-remote-access-plugin (--remove):
 installed c8y-remote-access-plugin package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Error:
  × Declaring supported operations
  ╰─▶ Creating the file failed: "/etc/tedge/operations/c8y/
      c8y_RemoteAccessConnect".

dpkg: error while cleaning up:
 installed c8y-remote-access-plugin package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 c8y-remote-access-plugin
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Environment (please complete the following information):**
 - OS [incl. version]: Debian 11
 - Hardware [incl. revision]: Raspberry Pi 3 (armv7)
 - System-Architecture [e.g. result of "uname -a"]: Linux raspberrypi 5.15.84-v7l+
 - thin-edge.io version [e.g. 0.1.0]: 0.10.0

**Additional context**

**Comment by gligorisaev** [comment]
@jarhodes314  I am still able to reproduce the mentioned error.
`
tedge.version:   0.10.0-75-g7566aff7
device.id:       remote_bug
Cumulocity IoT:  https://qaenvironment.eu-latest.cumulocity.com/apps/devicemanagement/index.html#/assetsearch?filter=*remote_bug*

----------------------------------------------------------
(pi:150) pi@raspberrypi:~ $ sudo rm -rf /etc/tedge/operations/c8y/c8y_RemoteAccessConnect
(pi:150) pi@raspberrypi:~ $ sudo apt-get purge c8y-remote-access-plugin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  c8y-remote-access-plugin*
0 upgraded, 0 newly installed, 1 to remove and 15 not upgraded.
After this operation, 2648 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 38283 files and directories currently installed.)
Removing c8y-remote-access-plugin (0.10.0) ...
Error: 
  × Removing supported operation at /etc/tedge/operations/c8y/c8y_RemoteAccessConnect
  ╰─▶ No such file or directory (os error 2)

dpkg: error processing package c8y-remote-access-plugin (--remove):
 installed c8y-remote-access-plugin package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Errors were encountered while processing:
 c8y-remote-access-plugin
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
