### ISSUE TITLE
upgrade path for mosquitto bridge configuration files across thin-edge.io releases

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2192]
**Is your feature improvement request related to a problem? Please describe.**

When mosquitto bridge configuration is changed in a new version of thin-edge.io, then the bridge configuration will not be updated until a manual `tedge reconnect c8y` (or `disconnect`, `connect`) is done. This leads to potential non-optimized bridge configuration from being activated, such changes include:

* clean session default setting (see #2159)
* updates to default configuration subscriptions (see #2168)

**Describe the solution you'd like**

The mosquitto cloud bridge configurations which are managed by thin-edge.io should be automatically updated in case of any changes to the thin-edge.io default settings.

Currently mosquitto bridge configuration can not be updated dynamically, so it is likely that a full mosquitto restart will be required for the new settings to take effect.

**Describe alternatives you've considered**

**Additional context**

**Comment by albinsuresh** [comment]
Here is how we are planning to address this:
1. Extract the bridge creation logic out from the `tedge` binary into a common lib, so that it is accessible to the mapper as well.
2. Add this bridge creation functionality into the mapper's `--init` option (or a new option, if `--init` is not appropriate).
3. `tedge connect` command will use this `--init` option to get the bridge created before starting the mapper service.
4. The mapper will call this `--init` option and restart mosquitto from its `postinst` script as part of the upgrade as well, if the bridge config already exists.

By making the bridge creation logic common, and making it accessible from the mapper, we avoid the dependency of the mapper on executing a `tedge` command to get the bridge created from its `postinst` script. This way, even if the `tedge` is on an older version, while the `tedge-mapper` package is upgraded, it won't cause any problems. Otherwise, we need to make sure that `tedge` is always upgraded first, before the mapper is. This may be acceptable in the current scheme of things, but making the mapper more independent is definitely better for future.

**Comment by reubenmiller** [comment]
> Add this bridge creation functionality into the mapper's --init option (or a new option, if --init is not appropriate).

Though I'm not sure if I agree with this point. As how do we make sure that the mapper init is run at the correct point in time (e.g. after the `c8y.url` is set by the user etc.)...this would introduce more problems if both the `tedge-mapper c8y --init` and `tedge connect c8y ...` command would be capable of creating the bridge file.

**Comment by Bravo555** [comment]
Part of the motivation behind this approach is to move establishing the connection out of `tedge` and into the related mappers. Of course this won't all be done at once, but this is good opportunity to move the mosquitto bridge configuration generation.

> As how do we make sure that the mapper init is run at the correct point in time (e.g. after the `c8y.url` is set by the user etc.)...this would introduce more problems if both the `tedge-mapper c8y --init` and `tedge connect c8y ...` command would be capable of creating the bridge file.

I'm not sure where the problem is. If the bridge file is already there, then `c8y.url` has to be set, so we can update. If the bridge file is not present, then we haven't yet connected and generating the configuration is a fallible operation, which we can report back to the user.

In this proposed solution, the bridge configuration generation would only live in the mapper. `tedge` would invoke it by spawning a new `tedge-mapper-c8y --init` process, or by calling into its API.

I'll think more about other possible solutions and describe their advantages and disadvantages in another comment.

**Comment by albinsuresh** [comment]
> Though I'm not sure if I agree with this point. As how do we make sure that the mapper init is run at the correct point in time (e.g. after the c8y.url is set by the user etc.)

Just to be clear, the `--init` option call from the `postinst` maintainer script would be called only when the bridge configuration exists (i.e, only during upgrades and not on the very first installation). The initial creation of the bridge config is controlled by the `tedge connect c8y` command itself, which just internally uses the `tedge-mapper-c8y --init` option for the same.

**Comment by Bravo555** [comment]
### Related issues

1. bridge definitions part of main `tedge` package
	- it should be the responsibility of the mapper to handle its bridge
	- it makes it harder to develop bridges, because each has to be handled by `tedge` in a custom way
	- does it cause any issues right now though?
2. mosquitto is restarted too early
	- because other packages depend on `tedge`, and newer versions of `tedge-*` components depend on newer versions of `tedge`, we have to upgrade `tedge` first
	- `tedge` manages system services like `mosquitto`, we shouldn't interact with system services in other packages
	- for this reason, the latest mosquitto can be restarted is in `tedge` postinst script, which is executed before any other components are upgraded
	- after `mosquitto` is restarted, old components can connect to newer bridge
	- ideally, we would start mosquitto back up after all the clients are upgraded as well
3. different components being online/offline at different times, which may produce race conditions/inconsistent data
3. Are there any other things that are impacted by upgrading that may need restarting or any special handling?

## Desired properties

Properties we want our solution to have, from most to least important:

- **resilient**: minimise room for weird errors/misconfigurations, have as few dependencies/assumptions as possible
- **automatic**: there should be no need for manual intervention from the user side
- **atomic**:
	- **vertically**: we don't want users to see partial/inconsistent state between cloud/broker/tedge clients, e.g. we don't want to see old clients using new bridge (topics might've changed so what clients published won't be sent to remote broker) and we don't want new clients using old bridge (vice versa)
	- **horizontally**: when we're connected to multiple clouds at the same time, we should additionally take precautions to make sure that due to upgrading different mappers at different times, there is no scenario where telemetry data is sent to a subset of clouds we're connected to, due to some mappers being up and some down
- **backwards compatible**: we don't want to change any established behaviours that users may rely on
- **minimal**: minimise the amount of new (possibly user-reachable) commands and features, reduce scope creep
- **implementation simplicity**: it should be simple to implement

## Ideal implementation

After thin-edge is upgraded, we have to perform the following steps in order to fulfil all the requirements and not have any old leftover configuration:

1. Disable mosquitto and mappers
2. Upgrade thin-edge packages
3. Update relevant bridge configuration files
4. Restart mosquitto
5. Start any clients that were stopped before the upgrade

However, due to different parts of thin-edge being split in different packages, the upgrade is made more difficult because packages are upgraded serially. It's not possible to stop mosquitto once, upgrade all the clients, and start mosquitto once after all are upgraded, because we don't know which package is upgraded last (but we know `tedge` is first)

The best would be to have a way of calling `tedge reconnect CONNECTED-CLOUD` automatically after update, but for that:

- all the packages would have to already be upgraded. `tedge` would be most fitting to put this reconnect logic into, but as it's a dependency of other packages, it will probably be upgraded first, but reconnect should be done last
- how to know to which clouds we're connected? We can look at which bridge conf files are present

Currently mosquitto and bridges are managed by `tedge` alone, and other packages are just clients connecting to the broker.

## Possible solutions

Below are some possible solutions, ranging from the simplest and most immediate, to the more complex, but addressing more upgrade issues long-term. The solution we decide on for this ticket doesn't need to fit completely in any of the below, it can be some combination of them.

### Just run `tedge reconnect CLOUD` on upgrade

Run `tedge reconnect aws/c8y/az` as part of `tedge` postinst. All 3 of them would have to be run to cover all the possible clouds. Alternatively, plain `tedge reconnect` could be added which only reconnects only to the clouds we're currently connected to.

Currently, running `reconnect` when we're not connected just does the same as `connect` because `disconnect` does not fail when we're not connected, so it effectively acts as a no-op. If we were to make `disconnect` fail when we're not connected:
- it would make it more predictable and consistent with `connect` which does fail if we're already connected
- `reconnect`, as just a sequence of `disconnect` and `connect` would be sufficient

`reconnect` would then have 2 failure modes:
- we were not connected in the first place, so we won't try to reconnect. This is expected most of the time, so failure there should be ignored 
- we were connected, but there was a problem when we tried to reconnect, this should fail and be reported to the user
that could be distinguished by the return code, but it may be a little clunky

- **resilient**: ? what should be done if there's an error when trying to reconnect?
- **automatic**: ✅ done as a `tedge` postinst
- **atomic**:
	**vertically**: ❌ `tedge` is upgraded first, after it finishes and new bridge is established, yet unupgraded daemons use the newer bridge. It may cause bugs if bridge changes are not forward-compatible (usually they're not)
	**horizontally**: ❌ `tedge reconnect` takes at least 5 seconds, so restarting 3 different clouds comes out to at least 15 seconds, which is plenty for differences to come up in telemetry data sent
- **backwards-compatible**: ❌ possible semantic change of reconnect command to handle when we're not already connected
- **minimal**: ✅ doesn't add any new commands (or only minimally extends current commands)
- **implementation simplicity**: ✅ simple to implement

- ❌ upgrade can take a lot of time because we're running up to 3 reconnects separately, each of which restarts mosquitto and runs the connection test

Doesn't address the additional issue 1) and 2).

### Add command to tedge which regenerates the bridge config and run it after upgrade

To go around the change in `reconnect` semantics from the previous solution, we can add yet another command to `tedge` like `tedge connect update-bridge [CLOUD]` which does not connect to the cloud, but updates the bridge for a given cloud, if specified, or any we're currently connected to. If no bridge is currently configured, then it's a noop.

All the bridge configuration files are updated at once, and then mosquitto is restarted. This doesn't run the connection test and only restarts mosquitto once, so time needed is shortened significantly.

Something else would then have to trigger mosquitto restart to finalize the reconnect.

- **resilient**: / The connection test is not run, so failure to connect will be harder to report
- **automatic**: ✅ done as a `tedge` postinst
- **atomic**:
	**vertically**: / mosquitto is not restarted during `tedge` upgrade, so it continues to run with the old bridge until it's restarted by mappers postinsts themselves or something after them. It's not ideal because it adds coupling between mappers and mosquitto, but it solves the problem
	**horizontally**: / if mosquitto is restarted in each mapper postinst, then it's not solved. If mosquitto is restarted only after all the mappers are updated, then it would be solved.
- **backwards-compatible**: ✅ behaviour of reconnect and other commands should stay unchanged
- **minimal**: ❌ adds another user-reachable command
- **implementation simplicity**: ✅

- ❌ exposed to users

Doesn't address additional issue 1).

### Move generating bridge configuration into the mapper

Writing the bridge configuration would then be achieved by running `tedge-mapper-c8y init` command or similar. This would introduce a dependency in `connect` command to actually spawn the mapper process and wait for it to succeed.

This would require a lot more work than the minimal solution of just running `reconnect` in postinst scripts, but would would start removing the coupling between main `tedge` package and the mappers, and would move bridge configuration for a given cloud into its respective mapper - which would arguably make more sense. Because bridge configuration definition is part of the mapper, this would fix the problem of older mapper using newer not-forward-compatible bridge.

But we would have to restart mosquitto directly in the mapper, or something else would have to restart it every time after the mapper is upgraded. We could do it in a postinst for every mapper, but it would make the upgrade not atomic horizontally, because different mappers would be upgraded and downed at different times while the rest work as usual, leading to telemetry data from different times missing at different clouds.

- - we would have to restart mosquitto from tedge-mapper, which may be surprising to users

- **resilient**: ?
- **automatic**: ?
- **atomic**:
	- **vertically**: ✅ fixes the issue, bridge is upgraded together with associated mapper
	- **horizontally**: ❌ different mappers are upgraded at different times, they come down and up at different times so sent telemetry data is inconsistent
- **backwards compatible**: / this would introduce failures in scenarios where `tedge connect c8y` is used but associated mapper is not installed. Technically not backwards compatible but this scenario is unexpected and unsupported, usually the mapper should be installed.
- **minimal**: ❌ This technically introduces an interface between `tedge` and `tedge-mapper-*` that we'd have to define and make sure to maintain as it would be a potential entry point for new user-made mappers.
- **implementation simplicity**: / More process spawning API, but I don't expect any obvious immediate difficulties

Partially addresses issue 1) and addresses issue 2).

### Move connecting to cloud to the mapper completely

- **resilient**: ✅
- **atomic**:
	- **vertically**: ✅ as before
	- **horizontally**: ❌ as before
- **backwards-compatible**: / as before
- **minimal**: ❌ as before
- **automatic**: ?
- **implementation simplicity**: ❌ Even more than in previous solution, dividing the connection process into mappers may be very complicated, there would perhaps complications, but it will have to be done eventually if we want to reach the level of extensibility that new mappers don't require changes to core `tedge` and can be developed in complete separation.

Addresses issues 1) and 2).

## Summary

The issue provided an opportunity to think more about the whole thin-edge.io upgrade experience and directions where we can go with it. I expect the resolution to this ticket to be some sort of a combination of possible solutions proposed above, more of a 1/2 to address the issue faster, with 3/4 being considered as a follow-up as part of another update-experience focused ticket. But it's worth to mention that doing 1/2 requires adding some coupling that may become problematic if we stay with it for too long.

If atomicity of the upgrade isn't really a big problem, then we can go with 1/2 for a longer time. If it is a problem, then it should probably be addressed sooner rather than later.

## Follow-ups

- Ensure updates are atomic, old clients don't use new bridge and vice versa:
	- add version information to MQTT client id of tedge daemons
	- write tests that checks if no old daemons are connected before the update is complete

**Comment by albinsuresh** [comment]
> This would introduce a dependency in connect command to actually spawn the mapper process and wait for it to succeed.

I don't think that this is a problem because the `tedge` utility, especially commands like `tedge connect`, was designed as a facade to orchestrate the spawning and interaction between different tedge components and other services, to ease the initial setup process. It already does things like starting/restarting processes like `tedge-agent` and even external processes like `mosquitto`. So, the same command interacting with the `tedge-mapper` binary as well isn't an issue at all and perfectly fits with what that utility was designed for.

Even for the long term, as long as we don't add any hard dependencies between `tedge` and other components, where it would be still possible to orchestrate the spawning of all those components without using `tedge` at all, we are good. And this attempt to move the bridge creation logic into the respective mappers themselves is a right step in the direction.

> different mappers are upgraded at different times, they come down and up at different times so sent telemetry data is inconsistent

On this point regarding horizontal atomic upgrades, this scenario is not gonna happen in the current scheme of things as the `tedge-mapper` is a single binary which encompasses all the cloud mappers. So, when we upgrade that package, we're essentially upgrading them all at once. And even during the mosquitto downtime caused by the restart, I don't think there's any possibility of telemetry data loss, as long as the clients don't drop the messages when the MQTT connectivity breaks as a result of the broker restart. Once the messages are delivered to the broker post-restart, they will be delivered to the respective mappers eventually, even if the mappers come up later, as their sessions with the broker are persistent.

> Ensure updates are atomic, old clients don't use new bridge and vice versa: add version information to MQTT client id of tedge daemons

Here by clients, I'm assuming that you just meant the mapper clients, as the other clients are not even aware of the bridge's existence and should stay that way. The proposal to add version info to the client IDs have other consequences, because using the same client id even across upgrades, is used to maintain persistent sessions with the broker, to make sure that any data published even during the upgrade are eventually delivered to the upgraded client.

**Comment by reubenmiller** [comment]
Given the long posts here, below is the decision about the direction of this ticket:

**Decision**

* Create single command to recreate the bridge configuration files if necessary, and restart the mosquitto broker if at least one bridge file was updated
* Don't move the bridge creation logic to the mapper. Reason: The mapper does not need to know all of the topics and is until now not used to configure things (only read).

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
- [x] QA has tested the function and it's functioning according description.
