### ISSUE TITLE
wrong state executed after workflow restart during a partition swap

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2495]
**Describe the bug**

Using the restart mechanism in the workflows causes a race condition during a firmware update when switching partitions if the mosquitto database is not up to date before switching partitions. This causes the incorrect workflow state to be executed after the restart.

**To Reproduce**

The following firmware_update workflow and log shows the invalid state transition after the "restart" state is executed.

[workflow-firmware_update-c8y-mapper-2023-12-01T130512.15038169Z.log](https://github.com/thin-edge/thin-edge.io/files/13527710/workflow-firmware_update-c8y-mapper-2023-12-01T130512.15038169Z.log)
[firmware_update.toml](https://github.com/thin-edge/thin-edge.io/files/13527732/firmware_update_toml.txt)

**Expected behavior**

The specified "after restart" state should be executed once a device is restarted.

**Screenshots**

**Environment (please complete the following information):**

|Property|Value|
|--------|-----|
|OS [incl. version]|`Poky (Yocto Project Reference Distro) 4.0.14 (kirkstone)`|
|Hardware [incl. revision]|`Raspberry Pi 4 Model B Rev 1.1`|
|System-Architecture|`Linux rpi4-dca632486720 5.15.34-v8 #1 SMP PREEMPT Tue Apr 19 19:21:26 UTC 2022 aarch64 GNU/Linux`|
|thin-edge.io version|`tedge 0.13.2~118+g8457fa6`|

**Additional context**

**Comment by reubenmiller** [comment]
The current workaround is to configure mosquitto to store its db on a persisted volume which is accessible across switching A/B partitions.

**Comment by didier-wenzek** [comment]
Fixed by https://github.com/thin-edge/thin-edge.io/pull/2527

The current state of a command instance is no more only ruled out by MQTT messages.
- Command states are stored in `/etc/tedge/.agent/workflows` or in `$(tedge config get agent.state.path)/workflows` if the `agent.state.path` directory exists.
- All the command successive states are published over MQTT as previously using retained messages.
- But, the agent only reacts to operation retained messages in a specific state: init and clear
- So, if a participant published an unexpected state, this test is ignored
- This is notably the case when a stale version of the mosquitto is restored.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
