### ISSUE TITLE
Restart Operation Stuck in Executing

### ISSUE THREAD

**Issue by ChrScha** [thin-edge/thin-edge.io#2542]
**Describe the bug**
Rasperry Pi 4 does restart after creating the restart operation in Cumulocity IoT. The operation status changes to EXECUTING, but after a successful reconnect the operation is not set to SUCCESSFUL. 

**Expected behavior**
I expected the c8y_Restart operation to be successful

 - tedge version: `0.13.2~229+g460f3eb`
 - Device: `Raspberry Pi 4`
 - PRETTY_NAME: `Raspbian GNU/Linux 10 (buster)`
 - Machine: `Linux raspberrypi 4 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU / Linux`
 - Architecture: `armhf`

**Comment by reubenmiller** [comment]
We've been making a few changes over the last few days which might address your situation, so could you please try updating thin-edge.io to the latest version `>=0.13.2~250+g742ae21` (on the main branch, since you're already using that).

Before you upgrade, you will also need to set the existing operation which are "stuck" in EXECUTING to FAILED. You can use the Cumulocity IoT REST API, or [go-c8y-cli](https://goc8ycli.netlify.app/) to do this:

```sh
c8y operations list --device 12345 --status EXECUTING | c8y operations update --status FAILED --failureReason "User cancelled operation"
```

After you have cleared all of the `EXECUTING` operations in Cumulocity, you can update thin-edge.io.

1. Update the thin-edge.io version (easiest just to re-use the install.sh script for now)
2. Restart the tedge-agent (for now this must be done, but we're working on a solution, https://github.com/thin-edge/thin-edge.io/issues/2501)
 
    ```sh
    sudo systemctl restart tedge-agent
    ```
3. Trigger a new restart operation from the Cumulocity IoT device management application

**Comment by ChrScha** [comment]
For me it does not fix it unfortunately. 
Nevertheless I need to do the update from debian 10 to 11 via SD card. 
Do you want me to keep the debian 10 for a while to test of the next version fixes it?

**Comment by reubenmiller** [comment]
> For me it does not fix it unfortunately. Nevertheless I need to do the update from debian 10 to 11 via SD card. Do you want me to keep the debian 10 for a while to test of the next version fixes it?

I'm not sure what the problem is and I really doubt it has anything to do with Debian 10. Can you provide some logs after you do an update?

```sh
journalctl -u tedge-agent -n 1000 > tedge-agent.log
```

**Comment by reubenmiller** [comment]
ah, what mosquitto version are you using? I suspect anything but mosquitto 2.0.18 will be problematic.

**Comment by gligorisaev** [comment]
I tried to reproduce this issue on many devices (RPI3, RPI4, RPI5), in many different variants of tedge versions, 0.13.2~229+g460f3eb also 5 before and 5 after this version,  but was not able to reproduce the bug.

I will retry with other mosquitto version (2.0.18)

**Comment by ChrScha** [comment]
Yes I use Mosquitto <2.0.0
Apt update did not help to get the latest.

Do you agree with this recommendation to get a recent Mosquitto version even though I have Debian 10 (Buster)??
https://stackoverflow.com/questions/67613899/how-to-update-mosquitto-to-latest-version-in-ubuntu 

1. uninstall the old mosquitto version:
```
sudo apt autoremove mosquitto
```
2. add mosquitto-dev PPA to your sources list :
```
sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa 
sudo apt-get update
```
3. install mosquitto:
```
sudo apt install mosquitto 
```

**Comment by reubenmiller** [comment]
> Yes I use Mosquitto <2.0.0 Apt update did not help to get the latest.
> 
> Do you agree with this recommendation to get a recent Mosquitto version even though I have Debian 10 (Buster)?? https://stackoverflow.com/questions/67613899/how-to-update-mosquitto-to-latest-version-in-ubuntu
> 
> 1. uninstall the old mosquitto version:
> 
> ```
> sudo apt autoremove mosquitto
> ```
> 
> 2. add mosquitto-dev PPA to your sources list :
> 
> ```
> sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa 
> sudo apt-get update
> ```
> 
> 3. install mosquitto:
> 
> ```
> sudo apt install mosquitto 
> ```

Yes updating to mosquitto 2.0.18 is highly recommended on any platform due to a string of bugs with earlier versions (mostly regarding the bridge functionality). However the problem you're going to face is actually accessing the mosquitto 2.0.18 version on Debian Buster. 

However I would recommend upgrading to Debian Bookworm as Buster only has about 6 months before it is [EOL](https://wiki.debian.org/DebianReleases), however even on Debian bookworm you have to configure the sid repository to access the desired mosquitto version.

**Comment by reubenmiller** [comment]
And generally following Ubuntu advice on Debian isn't recommended, as this might cause more problems then it solves.

**Comment by ChrScha** [comment]
Thanks guys, I appreciate your effort! If the Moquitto wasnt to old, I would have loved to do a firmware upgrade with tedge and Mender.

**Comment by reubenmiller** [comment]
> Thanks guys, I appreciate your effort! If the Moquitto wasnt to old, I would have loved to do a firmware upgrade with tedge and Mender.

Though doing a firmware (OS Update) requires you to flash your devices anyway...as OS updates requires an initial image to be flashed on the device to prepare the device for future OTA updates (e.g. create partitions etc.).
