### ISSUE TITLE
Error message "EOF while parsing a value at line 1 column 0" when clearing capabilities

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2739]
**Describe the bug**
Publishing an empty message to `config_snapshot`, `config_update`, and `log_upload` command metadata topics invokes an error message. 
```
EOF while parsing a value at line 1 column 0
```
Publishing an empty message to these topics are expected usecases since we need to publish empty retained messages to cancel the capabilities.

**To Reproduce**
Publish these messages below. (change the `child1` part to your device external ID)
```
tedge mqtt pub -r te/device/child1///cmd/config_snapshot ''
tedge mqtt pub -r te/device/child1///cmd/config_update ''
tedge mqtt pub -r te/device/child1///cmd/log_upload ''
```

Then you always get the same error messages on `te/errors` topic.

```
[te/device/child1///cmd/config_snapshot] 
[te/errors] EOF while parsing a value at line 1 column 0
[te/device/child1///cmd/config_update] 
[te/errors] EOF while parsing a value at line 1 column 0
[te/device/child1///cmd/log_upload] 
[te/errors] EOF while parsing a value at line 1 column 0
```

**Expected behavior**

No error messages.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [1.0.1]

**Additional context**

**Comment by Bravo555** [comment]
Note: the error is not sent as an MQTT message, but the error log is still printed:

```
ERROR c8y_mapper_ext::converter: crates/extensions/c8y_mapper_ext/src/converter.rs:139: Mapping error: EOF while parsing a value at line 1 column 0
```

I picked up the ticket to remove that error log as well since it bugged me a bit, but:

> Publishing an empty message to these topics are expected use-cases since we need to publish empty retained messages to cancel the capabilities.

Are there any more special considerations regarding this? I.e. what does "canceling the capabilities" entail? Should we run any cleanup code? Should the mapper mutate its capabilities struct to turn off the handling of an operation in response? Or should it publish its own retained registration message again so as to not leave the MQTT API in an inconsistent state (i.e. the mapper handles an operation but somebody else published a message that it does not, which is wrong)?

**Comment by Bravo555** [comment]
I'm just now noticing that this issue is actually bigger than it seems... :/

> The mapper should send an updated list of [supported operations `114`](https://cumulocity.com/docs/smartrest/mqtt-static-templates/#114) notifying the tenant that the device does no more support that operation.

I can see this happening with custom workflows when a dynamic reload happens and a workflow got removed, so the command is no longer available, but for built in operations, should we allow any MQTT client to send this clearing message and turn certain operations off?

Seems like original PR stalled due to there not really being a consensus of how exactly clearing capabilities should look like and how it relates to entity de-registration. Were there any other relevant discussions?

---

As for the target of this issue i.e. the error message, I think that even though clearing capabilities may be more complicated and require a little bit more work, for now we can at least tweak the log message so that it's actually more meaningful, e.g. `ERROR: Mapping error: EOF while parsing a value at line 1 column 0` -> `WARN: Ignoring clearing message on topic 'te/device/main///cmd/config_update': clearing capabilities is not currently supported`

**Comment by didier-wenzek** [comment]
> Seems like original PR stalled due to there not really being a consensus of how exactly clearing capabilities should look like and how it relates to entity de-registration. Were there any other relevant discussions?

@rina23q @reubenmiller Any answers?

**Comment by rina23q** [comment]
Indeed, the original PR was closed because we don't have a concrete design and meaning what is de-registration of a command capability. Removing the corresponded operation from c8y_SupportedOperations is necessary (= resend the `114` message). This means we need to remove files from `/etc/tedge/operations/c8y`. We might need more things?

In short, since the current error message is not well declarative, I like the @Bravo555 's proposal, just to change the error message as of now.

> for now we can at least tweak the log message so that it's actually more meaningful, e.g. ERROR: Mapping error: EOF while parsing a value at line 1 column 0 -> WARN: Ignoring clearing message on topic 'te/device/main///cmd/config_update': clearing capabilities is not currently supported

**Comment by reubenmiller** [comment]
Resolved.

These messages are no longer published to the `te/errors` topic, and below is the warning message visible in the tedge-mapper-c8y:

```
Dec 05 07:38:34 tedge tedge-mapper[3693]: 2024-12-05T07:38:34.751530077Z  WARN c8y_mapper_ext::converter: Ignoring command metadata clearing message: clearing capabilities is not currently supported topic="te/device/child1///cmd/log_upload"
```
