### ISSUE TITLE
Incorrect assertion in tedge-write test "doesnt_change_permissions_if_file_exists"

### ISSUE THREAD

**Issue by renaudcalmont** [thin-edge/thin-edge.io#2972]
Hi,
the result seems OK because the expectation is 644 and the root user umask on the testing system happens to be set at 022.
So 644 is the maximum file mode automatically applied but it isn't a proof that the code didn't change it.

https://github.com/thin-edge/thin-edge.io/blob/cf109f329b8513bc56b70e228fcc812a9cf94b05/crates/core/tedge_write/tests/main.rs#L76

Whithout any code change this test will fail immediately on a system where the root user umask is 077.
I strongly suggest to use 666 as the expected value for this test.

Moreover, it checks only the file mode but not the owner and group.
They happen to be reset to root:root, in contradiction with the code at https://github.com/thin-edge/thin-edge.io/blob/cf109f329b8513bc56b70e228fcc812a9cf94b05/crates/core/tedge_write/src/bin.rs#L66 which is supposed to prevent both mode and owner/group changes.

**Comment by Bravo555** [comment]
Hi, so in total following changes were made:

1. Most important, permissions and owner information were being reset if writing to a file that exists.
    This was fixed: `tedge-write` should now not overwrite original file owner/permissions.
    Also `tedge-write --help` was edited to clarify what should happen when file exists or doesn't exist.
2. Test were failing due to assumptions about default umask.
    We now set an umask as part of the test, so a case where `tedge-write` changes permissions to defaults should no longer be missed.
3. `tedge-write` can now take user/group id instead of only a name.

Some `tedge-write` tests were moved to Robot Framework, under `tests/RobotFramework/tests/tedge_write.robot`, you can run them with `just integration-test -s tedge_write`. Once it's merged you'll be able to run the test suite and verify if your issue is solved.

**Comment by gligorisaev** [comment]
QA can verify that this bug in test is fixed
