### ISSUE TITLE
c8y mapper panics with malformed registration messages

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2986]
**Describe the bug**
c8y mapper panics with this error.

```
thread 'tokio-runtime-worker' panicked at crates/core/tedge_api/src/store/pending_entity_store.rs:162:49:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-07-09T16:23:02.121644225Z ERROR Runtime: Actor CumulocityMapper-9 has finished unsuccessfully: JoinError(JoinError::Panic(Id(28), ...))    
```

**To Reproduce**
Run these commands in this order.

```sh
tedge mqtt pub -r 'te/device/child02//' '{"@type":"child-device"}'
tedge mqtt pub -r 'te/device/child02//' '{"@type":"service"}'
tedge mqtt pub -r 'te/device/child02//' '{"@type":"child-device"}'
```

**Expected behavior**
No panic. This scenario, changing `@type` should be treated as an error.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [main branch (after 1.1.1 release)]  https://github.com/thin-edge/thin-edge.io/commit/6fc5699c7f027a6bd1e3dd1f3cfd178fe66ab200

**Additional context**

**Comment by didier-wenzek** [comment]
This issue is quite serious. Trying to reproduce the error, I ended in a state where the mapper fails to start, panicking at `crates/core/tedge_api/src/store/pending_entity_store.rs:162:49`.

1. Sending a first `tedge mqtt pub -r 'te/device/child02//' '{"@type":"child-device"}'` is okay.
2. When sending an unexpected type `tedge mqtt pub -r 'te/device/child02//' '{"@type":"child-device"}'` makes the mapper crazy, taking 100% cpu.
3. If killed, the mapper fails then to restart.
4. The c8y mapper successfully restarts only after the child type is erased with `tedge mqtt pub -r 'te/device/child02//' ''`.

Note: for some unknown reason, there is no `/etc/tedge/device/inventory.json` on my device.

**Comment by rina23q** [comment]
@didier-wenzek 
Thanks for reproducing and creating a PR. The behaviour that you described is exactly what I found.

> Note: for some unknown reason, there is no /etc/tedge/device/inventory.json on my device.

`inventory.json` is not automatically created. Only when user wants to add fragments to c8y in a static way, the file is supposed to be created by user. Refer to [this](https://thin-edge.github.io/thin-edge.io/operate/c8y/custom-fragments/#static-fragments).

**Comment by gligorisaev** [comment]
I am not able to reproduce the bug, so it is solved
