### ISSUE TITLE
Mosquitto bridge configuration is not added to mosquitto.conf

### ISSUE THREAD

**Issue by GeraldRistow** [thin-edge/thin-edge.io#3218]
**Describe the bug**
Mosquitto bridge configuration is not added to mosquitto.conf

**To Reproduce**
Install Ubuntu 22.04 LTS or 24.04 LTS in a VM and follow the steps in [thin-edge.io](https://thin-edge.github.io/thin-edge.io/install/). When it comes to the tedge connect c8y command, the message says:

_Successfully created bridge connection!

Sending packets to check connection. This may take up to 2 seconds.

ERROR: Local MQTT publish has timed out.
Warning: Bridge has been configured, but Cumulocity connection check failed._

**Expected behavior**
No warning or error messge when issueing the tedge connect c8y command

**Screenshots**

**Environment (please complete the following information):**
 - OS Ubuntu 22.04 LTS and Ubuntu 24.04 LTS
 - Hardware Hyper-V on Dell laptop
 - System-Architecture [e.g. result of "uname -a"] Linux thin-edge1 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 - thin-edge.io version 1.3.1

**Additional context**
When I add manually the line _include_dir /etc/tedge/mosquitto-conf_ to the standard monquitto.conf file it works as desired. But then the bridge is always on since a disconnect does nothing there.
At installtion time it said: Detected mosquitto version >= 2.0.0, could that be the problem that the configuration has changed and is not recognized by thin-edge.io?

**Comment by reubenmiller** [comment]
@GeraldRistow I'm assuming that the `mosquitto` package has changed some of the default settings. The fix should be easy, though could you provide the following info?

* The location of the `mosquitto.conf` file. e.g. `find /etc -name mosquitto.conf`
*  The contents of the `mosuiqtto.conf` file

**Comment by reubenmiller** [comment]
Ok, we found the root cause. It was introduced in 73aeac6e161ac0213c7f115bbe3adc85cab8b8f9

The problem was caused by changing the tedge package dependency from **depends** to **suggests** which resulted in the installation order being affected as the `tedge` postinst maintainer script would be executed before mosquitto was installed and configured (so the `/etc/mosquitto/mosquitto.conf` file did not exist at this point in time).

The bug would manifest by the `tedge connect c8y` failing as the `include_dir /etc/tedge/mosquitto-conf` line would be missing from the `/etc/mosquitto/mosquitto.conf` file.

The `install.sh` script has been changed to install mosquitto before installing tedge.

@GeraldRistow the installation should be fixed now, can you please try again? You may need to remove `tedge-full` to try a clean installation.

**Comment by GeraldRistow** [comment]
Hi @reubenmiller, good job! Thanks for acting so fast, it works again...
