### ISSUE TITLE
idling behavior of tedge-mapper-sm-c8y

### ISSUE THREAD

**Issue by mbie-sag** [thin-edge/thin-edge.io#530]
**Describe the bug**
tedge-mapper-sm-c8y behaves unlike other mappers. If thin-edge is started in an unregistered state (public key not yet uploaded to tenant) to wait for registration the sm mapper will crash while everything else is able to stay in an idle state until public key is uploaded.  

**Expected behavior**
thin-edge should be able to stay in an idle state until connection can be set up (public key uploaded, internet access, ...)

**Environment (please complete the following information):**

* thin-edge.io version 0.4.0

AC:

* SM Mapper should retry to initialise and establish connection.

**Comment by makr11st** [comment]
Hi @mbie-sag,

I have been trying to reproduce as stated above but I failed.

My setup was:
new thin-edge.io intallation
no certificates created
no certificates uploaded

run: sudo tedge-mapper sm-c8y

Would you mind providing some more details, ideally steps to reproduce?

**Comment by makr11st** [comment]
Updated with reporter:


> ERROR sm-c8y-mapper:init: tedge_mapper::sm_c8y_mapper::mapper: FromElapsed(Elapsed(()))

> This is the error. The service is still running, but if I would upload a cert then, the device is registered but no Software Management fragment will appear within C8Y

The error messages is not clear, as the mapper requires specific information obtained from the cloud, due to registration not finished it cannot get them and therefore it will retry this every 5 minutes, but there is no feedback to the user.
Also, there is no mechanism to trigger this sooner than the 5 minutes passes.
