### ISSUE TITLE
Move installation-logic into Rust code (introducint tedge init)

### ISSUE THREAD

**Issue by cstoidner** [thin-edge/thin-edge.io#761]
Move logic of thin-edge package's installation-scripts and removal-scripts into Rust binaries. Therefore consider topics below:

  - Use of external tools (e.g. grep, sed, ...) shall be avoided. Instead Rust code/libraries shall be used.
    - To reduce external dependencies (tool missing or wrong version) and so reduce risc for failures.

  - At very beginning of the installation/removal procedure all required/touched external ressources (e.g. config files as "mosquitto.conf", external tools (if any left), ...) shall be checked for availibility/accessibility.
  - If one external ressource is not available installation/removal procedure shall fail before any action was performed.

    Reason: Risk for missing of any external resource might be low (especially when thin-edge was already installed before), but consquence would be fatal (especially for self-update via Cloud).
             Example: When mosquitto.conf was meanwhile removed or renamed, installation of new version fail, and also re-installation of old-one would fail. Result: Device would be disconnected from Could. 

AC:
- Creation of Users and Groups stays in maintainer scripts
- Modification of mosquitto configuration will also stay in maintainer scripts
- Modification of sudoers will also stay in maintainer scripts
- maintainer scripts will call init (no additional manual invocation by the user required)

- Creation of necessary tedge files and directories like config dirs, log dirs etc
- Creation of config extension directories for other external dependent services (mosquitto config, sudoers files etc)
- Creation of all necessary MQTT session names with the mosquitto broker (for agents, mappers etc)

**Comment by didier-wenzek** [comment]
I have questions about the pre-requisites of these init steps.

* Who creates the users and groups? 
* Who copies the `tedge` binaries in the appropriate bin directory?
* Who updates the tier config files (notably the sudoers but also the mosquitto.conf)?

I would assume the users, groups and executables created externally to match the specificities of each system.
So the `tedge --init` command can focus on the runtime requirements for thin-edge (directories, thin-edge exclusive configuration files, MQTT sessions).
I also think that in no case we should update tier config files, we just need to copy tedge specific config in `sudoers.d` and `mosquitto/conf.d`

**Comment by cstoidner** [comment]
> I would assume the users, groups and executables created externally to match the specificities of each system.
> So the tedge --init command can focus on the runtime requirements for thin-edge (directories, thin-edge exclusive configuration files, MQTT sessions).
> I also think that in no case we should update tier config files, we just need to copy tedge specific config in sudoers.d and mosquitto/conf.d

What do you mean with "created externally"? I suppose we shall have some kind of installation that completely setups thin-edge, so that it can be used out of the box (what we currently have with DEB packages). That means we need also to consider things like 
   - adding tedge specific config to mosquitto.conf
   - deploying system startup files (systemd by default) and required resources as users
   - ...?
   
From where do you expect these things shall be set up?

**Comment by didier-wenzek** [comment]
By "created externally" I mean not created by the thin-edge rust installer:
* I would avoid to create users and groups from this installer. This should be done on a system specific way by the main install script (an apt script on debian, an apk script on alpine, ...) that will call the `tedge --init`.
* We definitely need to avoid update system wide configuration as we currently do with `/etc/mosquitto.conf`. We must only add tedge specific config by adding files to `/etc/mosquitto/conf.d`. This can be done by `tedge --init`.
* Deploying system startup files is, from my point of view, also out of the scope of  `tedge --init`. These scripts are specific to a linux distribution and the best place to deploy them is the distribution specific installer script.

**Comment by albinsuresh** [comment]
To summarize, here is the set of actions that we can migrate from debian maintainer scripts to the new `tedge init` command:

1. Creation of necessary `tedge` files and directories like config dirs, log dirs etc
2. Creation of config extension directories for other external dependent services (mosquitto config, sudoers files etc)
3. Creation of all necessary MQTT session names with the mosquitto broker (for agents, mappers etc)

Actions that should remain in the distribution specific installers:

1. Creation of users and groups (Even though the `adduser` command is available in all major Linux distributions like Debian, Redhat and Alpine, their supported command-line options are different between distributions. There could be other Linux flavours where only `useradd` command is available and not `adduser`)
2. Installation of service manager definition files, as the service managers also vary from one distribution to another.

The `tedge init` command should delegate this initialization to other installed tedge components like `tedge-agent`, `tedge-mapper` etc via their own `init` commands. The `init` logic of these individual components can perform initialisations relevant to  those specific components rather than the `tedge` command itself initialising everything for every subcomponent. This allows selective initialisation of these components separately as well, if they were not installed at the time of `tedge init` execution.

**Comment by matthiasbeyer** [comment]
> Actions that should remain in the distribution specific installers:
> 
> 1. Creation of users and groups (Even though the adduser command is available in all major Linux distributions like Debian, Redhat and Alpine, their supported command-line options are different between distributions. There could be other Linux flavours where only useradd command is available and not adduser)
> 2. Installation of service manager definition files, as the service managers also vary from one distribution to another.

Yes, this is very different on different Linux distributions. Also, adding such things is just way out of scope of thin-edge (IMHO).

---

This looks like a nice and dandy way to get more into the codebase and I would like to tackle this issue, if we conclude what exact steps are necessary (I assume the points above are a good first approximation). I would most certainly need some guidance on details, though.

**Comment by didier-wenzek** [comment]
> This looks like a nice and dandy way to get more into the codebase and I would like to tackle this issue, if we conclude what exact steps are necessary (I assume the points above are a good first approximation). I would most certainly need some guidance on details, though.

It's a good idea. However, this a small issue touching somehow only the surface of the code.
