### ISSUE TITLE
Fix the `test_mqtt_server` to handle empty messages with the retain flag set

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#824]
As noted for the tests the feature to [Detect and reconcile alarms updated while mapper was down](https://github.com/thin-edge/thin-edge.io/commit/c15cfc4bee97473411ed173903f808c1132b8d8c), the test MQTT broker used by the integration tests doesn't properly handle the empty messages with the retain flag set.

* The empty retained messages don't reach the client under test, neither they are displayed on the test console.
* It's not clear if these messages are not properly sent by the `test_mqtt_client.rs` or not forwarded by the `test_mqtt_server.rs`.
* See [tedge_mapper/src/tests.rs](https://github.com/thin-edge/thin-edge.io/blob/c15cfc4bee97473411ed173903f808c1132b8d8c/crates/core/tedge_mapper/src/tests.rs#L122)

**Comment by albinsuresh** [comment]
What I observed is that the server is properly clearing retained messages on the server side, on receipt of an "empty retained message". What it fails to do, is to deliver the same **empty retained message** to active clients subscribed to the same topic. This behaviour is NOT consistent with the MQTT specification.

The [MQTT specification on retained messages in section 3.3.1.3](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html) states the following about the expected server behaviour for empty retained messages:
> A PUBLISH Packet with a RETAIN flag set to 1 and a payload containing zero bytes will be processed as normal by the Server and sent to Clients with a subscription matching the topic name.

Here is an `mqtt_channel` specific test reproducing this issue:

```rust
    #[tokio::test]
    #[serial]
    async fn test_retain_message_delivery() -> Result<(), anyhow::Error> {
        // Given an MQTT broker
        let broker = mqtt_tests::test_mqtt_broker();
        let mqtt_config = Config::default().with_port(broker.port);

        let topic = "retained/topic";
        let mqtt_config = mqtt_config.with_subscriptions(topic.try_into()?);

        // A client that subsribes to a topic.
        let mut first_subscriber = Connection::new(&mqtt_config).await?;

        //Raise retained alarm message
        let _ = broker
            .publish_with_opts(
                "retained/topic",
                "a retained message",
                QoS::AtLeastOnce,
                true,
            )
            .await
            .unwrap();

        //Expect the non-empty retained message to be delivered to first_subscriber
        assert_eq!(
            MaybeMessage::Next(message(topic, "a retained message")),
            next_message(&mut first_subscriber.received).await
        );

        //Clear the last raised retained message
        let _ = broker
            .publish_with_opts(
                "retained/topic",
                "", //Empty message indicates clear
                QoS::AtLeastOnce,
                true,
            )
            .await
            .unwrap();

        // Connect to the broker with the same session id
        let mut second_subscriber = Connection::new(&mqtt_config).await?;

        //Expect no messages to be delivered to this second_subscriber as the retained message is already cleared
        assert_eq!(
            MaybeMessage::Timeout,
            next_message(&mut second_subscriber.received).await
        );

        //Expect the empty retained message to be delivered to first_subscriber
        assert_eq!(
            MaybeMessage::Next(message(topic, "")),
            next_message(&mut first_subscriber.received).await
        );

        Ok(())
    }
```

This test will fail in the last assertion where the empty retained message is expected to be delivered to an already connected subscriber. The second-last assertion asserts that empty messages are indeed cleared on the server side so that they are never delivered to future clients.
