### ISSUE TITLE
Open up the data model for events without constraints on the fields/fragments that it can have

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#893]
**Is your feature request related to a problem? Please describe.**

Events are sometimes used to represent open-ended data and may not always have a uniform structure with just a `message` and a `timestamp`. So, a constrained structure for events data, with only `message` and `time` fields as it is today, really constraints its utility. Users may not always have a `message` field or sometimes they may want to more fields or fragments in it as well.

AC:
* Thin Edge JSON for events should not be constrained to just have a `message` field and `time` field
* Even the `message` field must be optional, just like `time` is.
* Additional fields or JSON fragments should be allowed.
* If the connected cloud supports custom fragments and fields (eg. c8y), its mapper should transfer those data also to the cloud.
* If the connected cloud only supports a text and timestamp for events, those can be derived from the `message` and `time` fields, with all other data ignored. Presence of other fields should not cause a failure but only be ignored.
* The overall event structure must still be a valid JSON and non-JSON data is out-of-scope
* The Cumulocity mapper will have to use JSON over MQTT for events below 16k and http for events above 16k

**Comment by didier-wenzek** [comment]
Rather than `"generic event"`, I think it's better to derive a missing event message from the event type i.e. the MQTT topic name.

**Comment by itsyitsy** [comment]
The second point was maybe a misunderstanding in the current implementation. I always wanted message field to be optional.

To the majority of points I can agree and also feel this would be good improvements.
The last point is probably derived from the point of having other fields than message and time? So to have this possibility we have to use JSON over MQTT rather than SmartREST. Right @albinsuresh ?

I want to mention that this has to be linked to #877 and that messages over the mqtt limitation are still a thing.

**Comment by albinsuresh** [comment]
> The second point was maybe a misunderstanding in the current implementation. I always wanted message field to be optional.

The `message` field is still optional from a Thin Edge JSON perspective. Only the c8y-mapper mandates that field. Anyway, PR #859 already has a fix that removes that restriction from c8y-mapper as well.

> To the majority of points I can agree and also feel this would be good improvements. The last point is probably derived from the point of having other fields than message and time? So to have this possibility we have to use JSON over MQTT rather than SmartREST. Right @albinsuresh ?

Yes we'll have to switch to JSON over MQTT to support such open event structures. But, we can continue using SmartREST, if the event message only contains any one or neither of these special fields(`message` or `time`) to save some bandwidth.

**Comment by mstoffel-sag** [comment]
Hi,

looks very well , to sum that up:

- We drop SmartRest Template altogether in favour of JSON over MQTT. (this makes things much easier because we don't have to take care of custom SmartRest templates)
- This goes in hand with the "Switch to REST" on payloads over 16kb

I think we should also look into supporting the Attachment Option of the Event API:

https://cumulocity.com/api/10.11.0/#tag/Attachments

This could be done by providing a reference to a file. ThinEdge then reads the file from the fs and uploads via REST.

**Comment by albinsuresh** [comment]
> I think we should also look into supporting the Attachment Option of the Event API:
> 
> https://cumulocity.com/api/10.11.0/#tag/Attachments
> 
> This could be done by providing a reference to a file. ThinEdge then reads the file from the fs and uploads via REST.

Sure, that requirement has been raised before as well. But, we'll be keeping that out of scope for this ticket and the support for binary payloads will be addressed in a separate ticket.
